Allow supplying NodeHandle for initParam
ros/robot_model pull request #168
Opened 2016-12-04 02:27 UTC by piyushk

Previously, initParam always constructs a default NodeHandle, which
works correctly as long as robot_description param and the node
calling initParam are in the same namespace. This is not true,
when initParam is called via a ros_control controller running in
the global namespace (gazebo), but robot_descriptions still need
to be namespaced. This backwards compatible change allows setting
the NodeHandle.

See https://github.com/ros-controls/ros_controllers/issues/244

2016-12-05 16:03 UTC, piyushk commented
Corresponding PR in ros_controllers: https://github.com/ros-controls/ros_controllers/pull/245

2016-12-06 14:08 UTC, bmagyar commented
Apart from providing backward compatibility with a consistent behaviour, this PR eases namespacing `robot_description`. It'd be a nice step towards multi robot systems and cases where multiple parts of the description are present in separate namespaces (proprietary control software).

:+1:  from me

2017-01-06 01:18 UTC, wjwwood commented
This would cause a ABI break as-is, and I'd prefer not to do that. You could instead add a new method, something like `initParamWithNodeHandle`, which took the additional second argument. We could consider adding the default parameter to `initParam` for ROS Lunar, but I'm not sure that there's a big advantage to that. Since you need to touch code to make use of this feature anyways, adding a new method shouldn't be any worse than extending the existing method's signature.

2017-01-09 13:29 UTC, bmagyar commented
:+1: Good idea @wjwwood , we'd need this in Kinetic

2017-01-09 21:41 UTC, wjwwood commented
I can forward/back port anything when preparing for release.

2017-01-10 05:32 UTC, piyushk commented
Sounds good. I'm swamped on other things at the moment, and I'll try and get back to this in a week or two.

2017-01-30 23:02 UTC, piyushk commented
@bmagyar, @wjwwood: Apologies for the delay. I didn't see a separate branch for the Jade release, but I've made the suggested change.

2017-01-30 23:15 UTC, wjwwood commented
Looks like CI is failing for Indigo and Jade, is that expected?

2017-01-30 23:47 UTC, piyushk commented
@wjwwood: My bad. Forgot a return statement. Checks are passing now.

2017-01-30 23:49 UTC, wjwwood commented
No worries that's why we have CI 😄.

@clalancette / @sloretz can you one of you guys review this change too?

2017-01-31 15:58 UTC, sloretz requested changes
I think package.xml may need to be updated too

2017-01-31 15:58 UTC, sloretz commented on urdf/include/urdf/model.h
> +#include <ros/ros.h>
@wjwwood correct me if I'm wrong, but I think the package.xml needs `<build_export_depend>roscpp</build_export_depend>` because of this addition

2017-01-31 15:58 UTC, sloretz commented on urdf/include/urdf/model.h
> +  bool initParamWithNodeHandle(const std::string& param, const ros::NodeHandle& nh = ros::NodeHandle());
Adding this looks good to me. It makes using the library easier.

I think the specific case of ros-controls/ros_controllers#244 could be solved by using [NodeHandle::resolveName("robot_description")](http://docs.ros.org/kinetic/api/roscpp/html/classros_1_1NodeHandle.html#a9eab8c5ff7ca9d3468d2a35dcd84ae40) and passing the fully qualified name into initParam()

2017-01-31 15:59 UTC, piyushk commented on urdf/include/urdf/model.h
> +  bool initParamWithNodeHandle(const std::string& param, const ros::NodeHandle& nh = ros::NodeHandle());
@sloretz: You're right. However, after discussion, we decided to go this route.

2017-01-31 16:13 UTC, piyushk commented on urdf/include/urdf/model.h
> +#include <ros/ros.h>
`build_export_depend` is unsupported in `package.xml` format 1, which is what urdf is using. I believe the format 1 build_depend did that behavior by default.

2017-01-31 16:17 UTC, sloretz approved these changes

2017-01-31 23:55 UTC, ipa-mdl commented on urdf/include/urdf/model.h
> +#include <ros/ros.h>
AFAIK in package format 1 "exported build depends" have to be declared as `run_depend`.

2017-02-09 22:21 UTC, piyushk commented
@wjwwood: Any chance we could push this one through since it's been approved? Thanks!

2017-02-10 00:53 UTC, merged

2017-02-10 01:04 UTC, piyushk commented
Awesome. Thanks!