Make rostest a test_depend
ros/robot_model pull request #221
Opened 2017-10-27 14:03 UTC by clalancette

While we are at it, change to package.xml format 2.

2017-10-27 15:18 UTC, sloretz requested changes

2017-10-27 15:18 UTC, sloretz commented on urdf/package.xml
> +  <exec_depend>tinyxml</exec_depend>
Since headers from `tinyxml` and `liburdfdom-headers-dev` are used in an installed header, do these need `<build_export_depend>` as well?

https://github.com/ros/robot_model/blob/58c19df6b22d90a8ca5d54db164499f71163a53d/urdf/include/urdf/model.h#L40-L47

2017-10-27 15:18 UTC, sloretz commented on urdf/package.xml
> +  <exec_depend>liburdfdom-headers-dev</exec_depend>
The latest package for `liburdfdom-headers-dev` on xenial has nothing but headers, so I don't think it needs to be an `<exec_depend>`. 

I'm surprised `liburdfdom-dev` is a run time dependency, but I don't see any non dev version in ubuntu and the latest package released to xenial does appear to have shared libraries in it.

2017-10-27 15:18 UTC, sloretz commented on urdf/package.xml
> +  <exec_depend>urdf_parser_plugin</exec_depend>
Looks like this package only has a single header in it, so I don't think it needs to be an `exec_depend`.

2017-11-03 15:59 UTC, sloretz approved these changes

2017-11-03 16:01 UTC, sloretz commented
@clalancette I made some changes in 1316141. If they look OK, I'll move this package to a new repo afterwards.

2017-11-03 17:19 UTC, clalancette reviewed
@sloretz Thanks for picking this up.  It looks good to me now, so feel free to merge (I can't approve my own PR :).

2017-11-03 17:20 UTC, merged